server:
  port: 8080

spring:

  main:
    allow-bean-definition-overriding: true

  jackson:
    default-property-inclusion: non_null
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  datasource:
    name: jwarden
    username: root
    password: secret
    url: jdbc:mysql://127.0.0.1/jwarden?createDatabaseIfNotExist=true
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


app:
  build-time: @buildTime@
  app-name: JWarden-Server
  java-version: @javaVersion@
  spring-boot-version: @springBootVersion@
  tomcat-version: @tomcatVersion@
  host: localhost:8080
  swagger:
    schemes: http, https
    base-path: test
