server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  jackson:
    default-property-inclusion: non_null
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

app:
  build-time: @buildTime@
  app-name: Yapam-Server
  java-version: @javaVersion@
  spring-boot-version: @springBootVersion@
  tomcat-version: @tomcatVersion@
  host: localhost:8080
  swagger-schemes:
    - http
    - https
