server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  jackson:
    default-property-inclusion: non_null
    mapper:
      DEFAULT_VIEW_INCLUSION: true

app:
  build-time: 1
  app-name: 1
  java-version: 1
  spring-boot-version: 1
  swagger-schemes:
    - http
    - https

yapam:
  registration-timeout: P1D

  mail:
    host: host.domain.com
    port: 587
    username: username
    password: password
    protocol: smtp
    test-connection: false
    message-sender: yapam@domain.com

  datasource:
    url: 'jdbc:h2:mem:'

keycloak:
  realm: "realm"
  resource: "resource"
  auth-server-url: "server"
