server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  jackson:
    default-property-inclusion: non_null
    mapper:
      DEFAULT_VIEW_INCLUSION: true

app:
  build-time: 1
  app-name: 1
  java-version: 1
  spring-boot-version: 1
  tomcat-version: 1
  swagger-schemes:
    - http
    - https

yapam:
  security:
    oauth:
      access-token-validity-period: P1D
      refresh-token-validity-period: P1D

  mail:
    host: host@domain.com
    port: 587
    username: username
    password: password
    protocol: smtp
    test-connection: false
    message-sender: yapam@yourdomain.com

  datasource:
    url: 'jdbc:h2:mem:'